---
- name: Install Apache on Ubuntu
  gather_facts: false
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: To print the message
      debug:
        msg: "Apache is successfully installed on EC2 machine."

    - name: Install zsh shell
      apt:
        name: zsh
        state: present

    - name: Print message
      debug:
        msg: "Zsh is present"

    - name: Print the message again
      debug:
        msg: "ZSH IS PRESENT!!!!!"

    - name: Install neofetch
      apt:
        name: neofetch
        state: present

    - name: Print message
      debug:
        msg: "Neofetch is installed!"

    - name: Uninstall zsh
      apt:
        name: zsh
        state: absent

    - name: Print the message
      debug:
        msg: "ZSH is successfully uninstalled"

    - name: Clear gathered facts from all currently targeted hosts
      meta: clear_facts

    
