---
- name: Check if test.txt exists and create it if not
  hosts: all
  become: yes
  tasks:
    - name: Check if test.txt exists in /home/ubuntu
      stat:
        path: /home/ubuntu/test.txt
      register: file_check

    - name: Print message if file exists
      debug:
        msg: "File test.txt exists in /home/ubuntu"
      when: file_check.stat.exists

    - name: Print message if file does not exist
      debug:
        msg: "No file found with the name test.txt"
      when: not file_check.stat.exists
