---
- name: Access Jenkins Variables
  hosts: all
  tasks:
    - name: Print Jenkins Variables
      debug:
        msg: |
          Jenkins Token: {{ jenkins_token }}
          Jenkins Username: {{ jenkins_username }}
          Jenkins Build URL: {{ jenkins_build_url }}
